dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

install:
  - wget https://ftp.fau.de/ubuntu/pool/universe/s/shellcheck/shellcheck_0.4.6-1_amd64.deb
  - sudo dpkg -i *.deb

script:
  - bash -xe ci/build-example-projects.sh
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then bash -xe ci/build-appimage.sh; fi

after_success:
  - |
    if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
        wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh appimagecraft*.AppImage
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
